{
  "$schema": "node_modules/wrangler/config-schema.json",
  "name": "libretv",
  "compatibility_date": "2026-08-31",
  "compatibility_flags": ["nodejs_compat"],
  "main": "./dist/server.mjs", 
  "assets": {
    "directory": "./dist/public"
  }
}
